# Generated by Django 4.1.2 on 2023-06-23 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idAutor', models.IntegerField()),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.IntegerField()),
                ('nombre', models.CharField(max_length=400)),
                ('precio', models.IntegerField()),
                ('categoria', models.IntegerField(choices=[[0, 'Romance'], [1, 'Fantasia'], [2, 'Romance Clasico']])),
                ('nuevo', models.BooleanField()),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tienda.autor')),
            ],
        ),
    ]
