# Generated by Django 4.1.2 on 2023-06-25 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_contacto'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='imagen',
            field=models.ImageField(null=True, upload_to='Libros'),
        ),
    ]
