# Generated by Django 4.1.2 on 2023-07-06 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0004_carrito_registro_elementocarrito_carrito_elementos_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Registro',
        ),
    ]
